### ISSUE TITLE
[Bug] Object initialization weaving is not working when class in the file hasn't joinpoints

### ISSUE THREAD

**Issue by TheCelavi** [goaop/framework#355]
As discussed, if there is no pointcut matching target, transformers are stopped. That leads to the fact that constructor weaving does not occurs in classes where it is being used. 

Source of issue seams to be in: `Go\Instrument\Transformer\CachingTransformer`, https://github.com/goaop/framework/blob/ed7760229190aa5521376ff2dde1d58ede7fbc5a/src/Instrument/Transformer/CachingTransformer.php#L117

I have played around trying to fix the issue: https://github.com/RunOpenCode/framework/blob/353eab93e2312be83aad28b3aeb5d245409b8be7/src/Instrument/Transformer/CachingTransformer.php#L118

I have changed `SourceTransformer`, method `transform()` must return either true or false, void is not an option. I have changed all other transformers in order to follow that signature.

Issue that I have now is that when I run functional test, every class with `new` keyword is weaved and every constructor of every class is being weaved as well. 

So I am missing something big... @lisachenko What I am doing wrong?

**Comment by TheCelavi** [comment]
Hm, `WeavingTransformer` depends on `AdviceMatcher`, it is only logical that `ConstructorExecutionTransformer` depends on `AdviceMatcher` as well, isn't? Something must check if `new X` in class code should be replaced with weaved constructor, right? Am I on right path here?

**Comment by lisachenko** [comment]
Hi, @TheCelavi!

Thank you for noticing and reporting this issue! It's indeed a bug with incorrect optimization logic of transformers, now it should be solved in #356

**Comment by TheCelavi** [comment]
@lisachenko Ok, but we still have issue :( now it does weaves initialization - but it does that for every class. We are getting same result as I have got when I opened issue. 

I have created class in project fixtures:


    <?php

    namespace Go\Tests\TestProject\Application;

    class MainFactory
    {
        public function create()
        {
            return new Main();
        }
    }

which is weaving path. 

I do get expected result in `framework/tests/Fixtures/project/var/cache/aspect/src/Application/MainFactory.php` which is:


    <?php

    namespace Go\Tests\TestProject\Application;

    class MainFactory
    {
        public function create()
        {
            return (\Go\Instrument\Transformer\ConstructorExecutionTransformer::getInstance()->{ Main::class}())->doSomething();
        }
    }


However, I got, per example `framework/tests/Fixtures/project/var/cache/aspect/src/Kernel/DefaultAspectKernel.php` as well (and not the only one), with code:
```

<?php

namespace Go\Tests\TestProject\Kernel;

use Go\Core\AspectContainer;
use Go\Core\AspectKernel;
use Go\Tests\TestProject\Aspect\DoSomethingAspect;
use Go\Tests\TestProject\Aspect\InitializationAspect;
use Go\Tests\TestProject\Aspect\Issue293Aspect;
use Go\Tests\TestProject\Aspect\LoggingAspect;
use Go\Tests\TestProject\Aspect\PropertyInterceptAspect;
use Psr\Log\NullLogger;

class DefaultAspectKernel extends AspectKernel
{
    /**
     * {@inheritdoc}
     */
    protected function configureAop(AspectContainer $container)
    {
        $container->registerAspect(\Go\Instrument\Transformer\ConstructorExecutionTransformer::getInstance()->{ LoggingAspect::class}(\Go\Instrument\Transformer\ConstructorExecutionTransformer::getInstance()->{ NullLogger::class}()));
        $container->registerAspect(\Go\Instrument\Transformer\ConstructorExecutionTransformer::getInstance()->{ DoSomethingAspect::class}());
        $container->registerAspect(\Go\Instrument\Transformer\ConstructorExecutionTransformer::getInstance()->{ PropertyInterceptAspect::class}());
        $container->registerAspect(\Go\Instrument\Transformer\ConstructorExecutionTransformer::getInstance()->{ Issue293Aspect::class}());
        $container->registerAspect(\Go\Instrument\Transformer\ConstructorExecutionTransformer::getInstance()->{ InitializationAspect::class}());
    }
}

```

I do not think that all constructors should be weaved. Does `ConstructorExecutionTransformer` should filter which classes construction to weave and which should not? And why does `ConstructorExecutionTransformer` does not need `AdviceMatcher`, or, should there be some class/service which would extract which class construction should be transformed from defined pointcuts?

I do not think that `AdviceMatcher` can be used, that is, it could be used, but like, a new instance which would match only `initialization` pointcut.

BTW -> you are wrong, weaving works even for:

     new Main;

and for:

    (new Main())->doSomething();

as well as for 

    (new Main)->doSomething();

which are a good news 👍

**Comment by TheCelavi** [comment]
Ok, I think I am right, `ConstructorExecutionTransformer` must use `AdviceMatcher` in order to filter out which constructor should and which constructor should not be transformed.

Second, `AdviceMatcher` should introduce new method `getInitializationAdvicesForClass` or `hasInitializationAdvicesForClass` -> with probably some result caching (because there is no reason to traverse advices several times for same class to get same answer, `new Main` can occur hundreds of times in code).

Third -> `ConstructorExecutionTransformer` then should use `AdviceMatcher` and check FQCN against `AdviceMatcher->hasInitializationAdvicesForClass()` in order to decide if constructor is going to be transformed or not.

Am I right? And are you going to deal with this or do you want me on this?

**Comment by lisachenko** [comment]
Ok, it's time to think a little bit deeper. You idea about using `AdviceMatcher` is good while you know each class name directly during analysis. But what I discovered is that fact than it's quite difficult to extract full class name that was given for `new` expression.

It can be FQDN, namespaced class name, relative class name, PHP expression, constant, whatever else. And we will know about class name only in runtime, so we need to wrap all `new` expressions in our codebase to intercept all possible initializations and check them in runtime.

We can improve this by spending more time on analysis of imports, namespace name and can detect 70-80% classical cases with `new SomeClassName` and if class hasn't initialization joinpoint, then leave this file as-is.

It can be done on AST-level, but we can not regenerate original source code from AST as it doesn't preserve white-spaces and formatting.

**Comment by TheCelavi** [comment]
Well, finally! -> I am right, a big moment for me here :D Ok, I do agree, it is imperative that code formatting is preserved. I will put my thinking hat on and will share any idea if I stumble upon it.

**Comment by TheCelavi** [comment]
I think that it can be done just by expanding logic of your `transform` method in `ConstructorExecutionTransformer`. There has to be map of `use` statements in file by looking for `T_USE` and `T_AS` tokens. Use statements are always before class is actually used, so map will be always up to date.

Now, you already extracting class name, only thing to do is to transform used class name (in whatever form it is used) into full qualified class name by consulting constructed map from `use` statements and check if there is initialization pointcut matching class.

So, I really think that it can be done. It is not easy, but it can be done.

However, this will not be supported anymore:

from:

    new stdClass(new static::$object[0]->name);

to:

    \Go\Instrument\Transformer\ConstructorExecutionTransformer::getInstance()->{ stdClass::class}(\Go\Instrument\Transformer\ConstructorExecutionTransformer::getInstance()->{ static::$object[0]->name});

that is, since not every `new` statement is intercepted, dynamic class initialization will not be intercepted. 

So - what do you think? Should we leave it as it is, or should we implement weaving filtering? (btw - I can modify `ConstructorExecutionTransformer`, no problem.)

**UPD:** What I don't like here is that when every `new` is weaved, every instance creation is done by using reflections, on top of that, there is that try/catch block of code which can really slow down code execution. If decision is to "leave it as it is", at least what can be done here is to optimize `protected static function construct($fullClassName, array $arguments = [])` method by: 
- not using try/catch block, `AdviceMatcher` can be used to determine if object instantiation  should be intercepted, or just initialized without interception
- implement some caching mechanism where previous matches/misses would be stored

**Comment by lisachenko** [comment]
My thoughts about that issue are following:
  - for all explicit class names we can check advisors at compile-time and transform only required files.
  - for complex expressions, we should use current solution and perform checks in runtime.

I also think about using parser-reflection deeper for transformers, so each transformer will also get as argument a `ReflectionFile` instance to have nice API for accessing information (eg to get list of use statements in the namespace). Ideally, combine `StreamMetaData` and reflection file API into one single object by moving all stuff from `StreamMetaData` into `ReflectionFile`.

And for distant future I have plans to switch all transformers to AST, see `goaop/ast-transformer` library. It would be so easy to find all `new` expressions and transform them with formatting preservation. :+1:

**Comment by TheCelavi** [comment]
Yes, agree. 

Now, someone has to do it :) do you want to take this one, or I can start to play around with it?

**Comment by lisachenko** [comment]
Do you have a willing to do this? If yes, then you could try to implement compile-time analysis of `new` expressions with explicit class names. I don't mind at all )

**Comment by TheCelavi** [comment]
Yeah, no problem.

**Comment by lisachenko** [comment]
So, we can move further, #362 is ready for review and we can access FQDN for class initializations and make compile-time decisions about should we transform particular file or not.
