### ISSUE TITLE
'\self' is an invalid class name

### ISSUE THREAD

**Issue by tpapic** [goaop/framework#415]
I installed [goaop-laravel-bridge](https://github.com/goaop/goaop-laravel-bridge) on my laravel app.

And I put this issue on that repo but they redirect me to you. [https://github.com/goaop/goaop-laravel-bridge/issues/15](https://github.com/goaop/goaop-laravel-bridge/issues/15)

` '\self' is an invalid class name {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): '\\self' is an invalid class name at npp/project/api/storage/app/aspect/_proxies/app/User.php/App/User.php:1055)
`
Method which has this error 

```
/**
     * Create a new pivot model instance.
     *
     * @param  \Illuminate\Database\Eloquent\Model  $parent
     * @param  array  $attributes
     * @param  string  $table
     * @param  bool  $exists
     * @param  string|null  $using
     * @return \Illuminate\Database\Eloquent\Relations\Pivot
     */
    public function newPivot(\self $parent, array $attributes, $table, $exists, $using = NULL)
    {
        return self::$__joinPoints['method:newPivot']->__invoke($this, \array_slice([$parent, $attributes, $table, $exists, $using], 0, \func_num_args()));
    }
```

PHP-version: 7.1.23
Laravel version: 5.5

**Comment by lisachenko** [comment]
Hi, @tpapic! Sorry for the late reply.

This issue with `self` should be fixed in #397. You should update to >=2.3.0 to have a fix for that.

**Comment by lisachenko** [comment]
Instead of `self` you should see full class name in generated proxies.

**Comment by SerafimArts** [comment]
Version 2.3.x does not fix the problem. Using goap with Laravel is currently not possible.

![image](https://user-images.githubusercontent.com/2461257/58255737-50fece80-7d76-11e9-8fa5-1b52d0f64f65.png)

# Reproduction

- `composer create-project laravel/laravel`
- `cd laravel`
- `composer require goaop/goaop-laravel-bridge`
- `php artisan vendor:publish --provider="Go\Laravel\GoAopBridge\GoAopServiceProvider"`
- `php artisan serve --host=0.0.0.0 --port=8000`
- Open `127.0.0.1:8000` in browser

During the request, the server writes an errors:
1) `NOTICE: PHP message: PHP Fatal error:  '\self' is an invalid class name in xxx on line 924`
2) `NOTICE: PHP message: PHP Fatal error:  Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in /var/www/dsp.localhost/vendor/laravel/framework/src/Illuminate/Container/Container.php:790`
